openapi: 3.0.0
info:
  version: 1.0.0
  title: Formatif 1
  description: Services Web H2022
  
servers: 
  - url: http://localhost/formatif1_serviceweb_h2022
paths:
  /:
    get:
      tags:
        - Général
      summary: Message de bienvenue
      responses:
        '200': 
          description: 
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                    message : 'Bon examen à tous!!'
  